version: "3.91"
services:
  app:
    build:
      context: ./docker/ 
      dockerfile: Dockerfile      
    image: local_image/jupyter      
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)  --notebook-dir=jupyter_folder
    stop_signal: SIGINT 
    environment:
      - TZ=${timezone}    
    volumes: 
      - type: bind
        source: ${home_folder}
        target: /home/jovyan/work       
    ports:
      - "${app_ports}"    
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"      

 