version: "3.9"
services:
  jupyter:
    build:
      context: ./docker/ 
      dockerfile: Dockerfile        
      args:
         NB_USER: "my-user"
    user: root
    image: local_image/jupyter     
    working_dir: /home/my-user/work
    ports:
      - "${app_ports}" 
    volumes: 
    - type: bind
      source: ${notebook_folder}
      target: /home/my-user/work   
    environment: 
      - CHOWN_HOME=yes
      - restartable=yes 
      - TZ=${timezone} 
      - DOCKER_STACKS_JUPYTER_CMD=notebook
    #stdin_open: true
    #tty: true
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''" 