version: "3.9"
services:
  jupyter:
    build:
      context: ./docker/ 
      dockerfile: Dockerfile        
      args:
         NB_USER: "${user}"
    user: root
    image: local_image/jupyter     
    working_dir: /home/${user}/work
    ports:
      - "${app_ports}" 
    volumes: 
    - type: bind
      source: ${notebook_folder}
      target: /home/${user}/work   
    - type: bind
      source: ${data_folder}
      target: /home/${user}/work/data        
    - type: bind
      source: C:\git\PY\utils
      target: /home/${user}/work/utils     
    environment: 
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS=-R    
      - restartable=yes 
      - TZ=${timezone} 
      - DOCKER_STACKS_JUPYTER_CMD=notebook
      - NB_USER=${user}
    #stdin_open: true
    #tty: true
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''" 